### ISSUE TITLE
Link to sample file CSV is broken

### ISSUE THREAD

**Issue by zx8754** [whussain2/ShinyAIM#2]
https://chikudaisei.shinyapps.io/shinyaim/

This link is broken:
https://github.com/whussain2/ShinyAIM/blob/master/Samplefiles/samplefile1_manhattan.csv

Because we have typo in `samplefile1_manhatt[e]n.csv`:
https://github.com/whussain2/ShinyAIM/blob/master/Samplefiles/samplefile1_manhatten.csv

**Comment by whussain2** [comment]
Thanks for catching this typo. Corrected the name of the sample file.
